Revert "arm64: crypto: add NEON accelerated XOR implementation"
This reverts commit b23ce89bfac9c004187afefb5402c87b0d28b8be.

In file included from ../../../../../../kernel/samsung/r3q/arch/arm64/lib/xor-neon.c:14:
In file included from ../../../../../../kernel/samsung/r3q/arch/arm64/include/asm/neon-intrinsics.h:36:
In file included from ../../../../../../prebuilts/clang/host/linux-x86/clang-r487747c/lib/clang/17/include/arm_neon.h:35:
/usr/include/stdint.h:96:23: error: typedef redefinition with different types ('unsigned int' vs 'unsigned long')
typedef unsigned int            uintptr_t;
                                ^
../../../../../../kernel/samsung/r3q/include/linux/types.h:40:24: note: previous definition is here
typedef unsigned long           uintptr_t;
                                ^
1 error generated.
make[2]: *** [/nonsec/evoxbuild/rom_build/kernel/samsung/r3q/scripts/Makefile.build:364: arch/arm64/lib/xor-neon.o] Error 1
make[1]: *** [/nonsec/evoxbuild/rom_build/kernel/samsung/r3q/Makefile:1271: arch/arm64/lib] Error 2
make[1]: *** Waiting for unfinished jobs....